import { MigrationInterface, QueryRunner } from "typeorm";

export class TypeImage1780602596659 implements MigrationInterface {
    name = 'TypeImage1780602596659'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dealership_reviews" DROP CONSTRAINT "FK_dealership_reviews_dealership_id"`);
        await queryRunner.query(`ALTER TABLE "dealership_reviews" DROP CONSTRAINT "FK_dealership_reviews_profile_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_category_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_profile_id"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_reports_category_id"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_reports_reporter_profile_id"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_reports_target_dealership_id"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_reports_target_profile_id"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_reports_target_vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" DROP CONSTRAINT "FK_chat_participant_state_chat_id"`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" DROP CONSTRAINT "FK_chat_participant_state_last_read_message_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" DROP CONSTRAINT "FK_vehicle_prices_vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" DROP CONSTRAINT "FK_vehicle_views_profile_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" DROP CONSTRAINT "FK_vehicle_views_vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" DROP CONSTRAINT "FK_vehicle_list_items_vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" DROP CONSTRAINT "FK_vehicle_list_items_vehicle_list_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_lists" DROP CONSTRAINT "FK_vehicle_lists_profile_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_shares" DROP CONSTRAINT "FK_vehicle_shares_profile_id"`);
        await queryRunner.query(`ALTER TABLE "vehicle_shares" DROP CONSTRAINT "FK_vehicle_shares_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dealership_reviews_dealership_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tickets_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tickets_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tickets_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reports_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reports_reporter_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reports_target_type_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reports_target_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reports_target_dealership_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reports_target_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_participant_state_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_vehicle_prices_one_active_per_vehicle"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vehicle_views_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vehicle_views_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vehicle_list_items_vehicle_list_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vehicle_list_items_vehicle_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vehicle_lists_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vehicle_shares_vehicle_id"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "CHK_reports_target_fks"`);
        await queryRunner.query(`ALTER TABLE "report_categories" DROP CONSTRAINT "UQ_report_categories_slug_target_type"`);
        await queryRunner.query(`ALTER TABLE "report_categories" DROP CONSTRAINT "UQ_report_categories_name_target_type"`);
        await queryRunner.query(`ALTER TABLE "vehicle_types" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_price_status" RENAME TO "vehicle_price_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_prices_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ALTER COLUMN "status" TYPE "public"."vehicle_prices_status_enum" USING "status"::"text"::"public"."vehicle_prices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_price_status_old"`);
        await queryRunner.query(`ALTER TABLE "dealership_reviews" ADD CONSTRAINT "FK_47cc9eef3db42916ce183a05998" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dealership_reviews" ADD CONSTRAINT "FK_0ac5a1b7bfdcb3b44cc8df6bb40" FOREIGN KEY ("dealership_id") REFERENCES "dealerships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_32a7f0e4e32a46a094b55f7c25c" FOREIGN KEY ("category_id") REFERENCES "ticket_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_fbcb5e6bcbf6e847e82e9cfd838" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_23d2ada1e9df0834c42df8d0fb0" FOREIGN KEY ("category_id") REFERENCES "report_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_e8b454e804d7344ec8b1b35687a" FOREIGN KEY ("reporter_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_6565e43018794d64335cc7724cd" FOREIGN KEY ("target_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_8597335e53ba39ca6f9dd2eb580" FOREIGN KEY ("target_dealership_id") REFERENCES "dealerships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_58de1a2fce02ab4942361259239" FOREIGN KEY ("target_vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" ADD CONSTRAINT "FK_9364ea3eb2f7704ece38c6e1eae" FOREIGN KEY ("last_read_message_id") REFERENCES "chat_messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" ADD CONSTRAINT "FK_dd98cb1438bf6767f5eba3ded6f" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ADD CONSTRAINT "FK_b90eb8a5afdbecd2b181412a040" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" ADD CONSTRAINT "FK_12244f09882ac38865d2133f5c4" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" ADD CONSTRAINT "FK_bf9a638e57e2f7d1226417c1ee0" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" ADD CONSTRAINT "FK_0a9d6fa86104649a8cb357d1ce2" FOREIGN KEY ("vehicle_list_id") REFERENCES "vehicle_lists"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" ADD CONSTRAINT "FK_e12d523362c7ffdb724a534436c" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_lists" ADD CONSTRAINT "FK_2c5ede6d6b58840a2c74620c23c" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_shares" ADD CONSTRAINT "FK_1c6beddff84b49560e80763b050" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_shares" ADD CONSTRAINT "FK_b5989fe8eb0bfbe9e12b88a6eed" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle_shares" DROP CONSTRAINT "FK_b5989fe8eb0bfbe9e12b88a6eed"`);
        await queryRunner.query(`ALTER TABLE "vehicle_shares" DROP CONSTRAINT "FK_1c6beddff84b49560e80763b050"`);
        await queryRunner.query(`ALTER TABLE "vehicle_lists" DROP CONSTRAINT "FK_2c5ede6d6b58840a2c74620c23c"`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" DROP CONSTRAINT "FK_e12d523362c7ffdb724a534436c"`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" DROP CONSTRAINT "FK_0a9d6fa86104649a8cb357d1ce2"`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" DROP CONSTRAINT "FK_bf9a638e57e2f7d1226417c1ee0"`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" DROP CONSTRAINT "FK_12244f09882ac38865d2133f5c4"`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" DROP CONSTRAINT "FK_b90eb8a5afdbecd2b181412a040"`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" DROP CONSTRAINT "FK_dd98cb1438bf6767f5eba3ded6f"`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" DROP CONSTRAINT "FK_9364ea3eb2f7704ece38c6e1eae"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_58de1a2fce02ab4942361259239"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_8597335e53ba39ca6f9dd2eb580"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_6565e43018794d64335cc7724cd"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_e8b454e804d7344ec8b1b35687a"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_23d2ada1e9df0834c42df8d0fb0"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_fbcb5e6bcbf6e847e82e9cfd838"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_32a7f0e4e32a46a094b55f7c25c"`);
        await queryRunner.query(`ALTER TABLE "dealership_reviews" DROP CONSTRAINT "FK_0ac5a1b7bfdcb3b44cc8df6bb40"`);
        await queryRunner.query(`ALTER TABLE "dealership_reviews" DROP CONSTRAINT "FK_47cc9eef3db42916ce183a05998"`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_price_status_old" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ALTER COLUMN "status" TYPE "public"."vehicle_price_status_old" USING "status"::"text"::"public"."vehicle_price_status_old"`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_prices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_price_status_old" RENAME TO "vehicle_price_status"`);
        await queryRunner.query(`ALTER TABLE "vehicle_types" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "report_categories" ADD CONSTRAINT "UQ_report_categories_name_target_type" UNIQUE ("name", "target_type")`);
        await queryRunner.query(`ALTER TABLE "report_categories" ADD CONSTRAINT "UQ_report_categories_slug_target_type" UNIQUE ("slug", "target_type")`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "CHK_reports_target_fks" CHECK ((((target_type = 'profile'::reports_target_type_enum) AND (target_profile_id IS NOT NULL) AND (target_dealership_id IS NULL) AND (target_vehicle_id IS NULL)) OR ((target_type = 'dealership'::reports_target_type_enum) AND (target_dealership_id IS NOT NULL) AND (target_profile_id IS NULL) AND (target_vehicle_id IS NULL)) OR ((target_type = 'vehicle'::reports_target_type_enum) AND (target_vehicle_id IS NOT NULL) AND (target_profile_id IS NULL) AND (target_dealership_id IS NULL))))`);
        await queryRunner.query(`CREATE INDEX "IDX_vehicle_shares_vehicle_id" ON "vehicle_shares" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_vehicle_lists_profile_id" ON "vehicle_lists" ("profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_vehicle_list_items_vehicle_id" ON "vehicle_list_items" ("vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_vehicle_list_items_vehicle_list_id" ON "vehicle_list_items" ("vehicle_list_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_vehicle_views_created_at" ON "vehicle_views" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_vehicle_views_vehicle_id" ON "vehicle_views" ("vehicle_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_vehicle_prices_one_active_per_vehicle" ON "vehicle_prices" ("vehicle_id") WHERE (status = 'active'::vehicle_price_status)`);
        await queryRunner.query(`CREATE INDEX "IDX_chat_participant_state_user_id" ON "chat_participant_state" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_reports_target_vehicle_id" ON "reports" ("target_vehicle_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_reports_target_dealership_id" ON "reports" ("target_dealership_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_reports_target_profile_id" ON "reports" ("target_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_reports_target_type_status" ON "reports" ("status", "target_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_reports_reporter_profile_id" ON "reports" ("reporter_profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_reports_category_id" ON "reports" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tickets_status" ON "tickets" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_tickets_profile_id" ON "tickets" ("profile_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tickets_category_id" ON "tickets" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dealership_reviews_dealership_id" ON "dealership_reviews" ("dealership_id") `);
        await queryRunner.query(`ALTER TABLE "vehicle_shares" ADD CONSTRAINT "FK_vehicle_shares_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_shares" ADD CONSTRAINT "FK_vehicle_shares_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_lists" ADD CONSTRAINT "FK_vehicle_lists_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" ADD CONSTRAINT "FK_vehicle_list_items_vehicle_list_id" FOREIGN KEY ("vehicle_list_id") REFERENCES "vehicle_lists"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_list_items" ADD CONSTRAINT "FK_vehicle_list_items_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" ADD CONSTRAINT "FK_vehicle_views_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_views" ADD CONSTRAINT "FK_vehicle_views_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_prices" ADD CONSTRAINT "FK_vehicle_prices_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" ADD CONSTRAINT "FK_chat_participant_state_last_read_message_id" FOREIGN KEY ("last_read_message_id") REFERENCES "chat_messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participant_state" ADD CONSTRAINT "FK_chat_participant_state_chat_id" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_target_vehicle_id" FOREIGN KEY ("target_vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_target_profile_id" FOREIGN KEY ("target_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_target_dealership_id" FOREIGN KEY ("target_dealership_id") REFERENCES "dealerships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_reporter_profile_id" FOREIGN KEY ("reporter_profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_category_id" FOREIGN KEY ("category_id") REFERENCES "report_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_category_id" FOREIGN KEY ("category_id") REFERENCES "ticket_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dealership_reviews" ADD CONSTRAINT "FK_dealership_reviews_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dealership_reviews" ADD CONSTRAINT "FK_dealership_reviews_dealership_id" FOREIGN KEY ("dealership_id") REFERENCES "dealerships"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
