import { PickType } from "@nestjs/mapped-types";

import { FindAllVehiclesHttpDto } from "@/src/contexts/vehicles/infrastructure/http-api/v1/find-all-vehicles/find-all-vehicles.http-dto";

export class AlertFiltersHttpDto extends PickType(FindAllVehiclesHttpDto, [
  "type_slug",
  "makes_slugs",
  "models_slugs",
  "since_price",
  "until_price",
  "price_offer",
  "service_slugs",
  "provinces_slugs",
  "comunities_slugs",
  "municipalities_slugs",
  "lat",
  "lng",
  "radius",
  "publisher_types",
  "is_seller_featured",
  "warranty_slugs",
  "since_year",
  "until_year",
  "since_mileage",
  "until_mileage",
  "transmission_types",
  "fuel_type_slugs",
  "traction_slugs",
  "power_since",
  "power_until",
  "displacement_since",
  "displacement_until",
  "dgt_label_ids",
  "autonomy_since",
  "battery_capacity_since",
  "battery_capacity_until",
  "time_to_charge",
  "features_slugs",
  "color_slugs",
  "cuota_slugs",
] as const) {}
