import type { FeatureUiCategorySlug } from "./feature-category.constants";

export interface FeatureCatalogSeedItem {
  name: string;
  category: FeatureUiCategorySlug;
}

export const FEATURE_CATALOG_SEED: FeatureCatalogSeedItem[] = [
  { category: "seguridad_asistentes", name: "ABS" },
  { category: "seguridad_asistentes", name: "Control de estabilidad" },
  { category: "seguridad_asistentes", name: "Control de tracción" },
  {
    category: "seguridad_asistentes",
    name: "Airbags frontales, laterales y de cortina",
  },
  { category: "seguridad_asistentes", name: "ISOFIX" },
  { category: "seguridad_asistentes", name: "Control de presión de neumáticos" },
  {
    category: "seguridad_asistentes",
    name: "Frenada automática de emergencia",
  },
  { category: "seguridad_asistentes", name: "Aviso de colisión" },
  { category: "seguridad_asistentes", name: "Detector de ángulo muerto" },
  {
    category: "seguridad_asistentes",
    name: "Aviso y mantenimiento de carril",
  },
  { category: "seguridad_asistentes", name: "Alerta de tráfico cruzado" },
  { category: "seguridad_asistentes", name: "Reconocimiento de señales" },
  { category: "seguridad_asistentes", name: "Detector de fatiga" },
  { category: "seguridad_asistentes", name: "Control de crucero" },
  { category: "seguridad_asistentes", name: "Control de crucero adaptativo" },
  { category: "seguridad_asistentes", name: "Limitador de velocidad" },
  {
    category: "seguridad_asistentes",
    name: "Asistente de arranque en pendiente",
  },
  { category: "seguridad_asistentes", name: "Control de descenso" },
  { category: "seguridad_asistentes", name: "Visión nocturna" },
  { category: "seguridad_asistentes", name: "Alarma antirrobo" },

  { category: "aparcamiento", name: "Sensores delanteros" },
  { category: "aparcamiento", name: "Sensores traseros" },
  { category: "aparcamiento", name: "Cámara trasera" },
  { category: "aparcamiento", name: "Cámara de 360°" },
  { category: "aparcamiento", name: "Aparcamiento automático" },
  { category: "aparcamiento", name: "Aparcamiento remoto" },

  { category: "confort", name: "Aire acondicionado" },
  { category: "confort", name: "Climatizador" },
  {
    category: "confort",
    name: "Climatizador bizona, trizona o de cuatro zonas",
  },
  { category: "confort", name: "Asientos calefactados" },
  { category: "confort", name: "Asientos ventilados" },
  { category: "confort", name: "Asientos con masaje" },
  { category: "confort", name: "Asientos eléctricos" },
  { category: "confort", name: "Memoria de asientos" },
  { category: "confort", name: "Volante calefactable" },
  { category: "confort", name: "Volante multifunción" },
  { category: "confort", name: "Levas en el volante" },
  { category: "confort", name: "Acceso sin llave" },
  { category: "confort", name: "Arranque sin llave" },
  { category: "confort", name: "Portón trasero eléctrico" },
  { category: "confort", name: "Apertura del maletero manos libres" },
  { category: "confort", name: "Cierre asistido de puertas" },
  { category: "confort", name: "Parabrisas calefactable" },
  { category: "confort", name: "Calefacción auxiliar" },

  { category: "multimedia_conectividad", name: "Pantalla táctil" },
  { category: "multimedia_conectividad", name: "Navegador" },
  { category: "multimedia_conectividad", name: "Cuadro de instrumentos digital" },
  { category: "multimedia_conectividad", name: "Head-Up Display" },
  { category: "multimedia_conectividad", name: "Bluetooth" },
  { category: "multimedia_conectividad", name: "Conexión USB" },
  { category: "multimedia_conectividad", name: "Apple CarPlay" },
  { category: "multimedia_conectividad", name: "Android Auto" },
  {
    category: "multimedia_conectividad",
    name: "Apple CarPlay y Android Auto inalámbricos",
  },
  { category: "multimedia_conectividad", name: "Cargador inalámbrico" },
  { category: "multimedia_conectividad", name: "Equipo de sonido premium" },
  { category: "multimedia_conectividad", name: "Radio digital DAB" },
  { category: "multimedia_conectividad", name: "Control por voz" },
  { category: "multimedia_conectividad", name: "Conexión Wi-Fi" },
  { category: "multimedia_conectividad", name: "Sistema multimedia trasero" },

  { category: "iluminacion_exterior", name: "Faros LED" },
  { category: "iluminacion_exterior", name: "Faros Matrix LED" },
  { category: "iluminacion_exterior", name: "Faros adaptativos" },
  { category: "iluminacion_exterior", name: "Faros de xenón" },
  { category: "iluminacion_exterior", name: "Luces largas automáticas" },
  { category: "iluminacion_exterior", name: "Faros antiniebla" },
  {
    category: "iluminacion_exterior",
    name: "Luces y limpiaparabrisas automáticos",
  },
  { category: "iluminacion_exterior", name: "Retrovisores eléctricos" },
  { category: "iluminacion_exterior", name: "Retrovisores calefactados" },
  {
    category: "iluminacion_exterior",
    name: "Retrovisores plegables eléctricamente",
  },
  { category: "iluminacion_exterior", name: "Techo solar" },
  { category: "iluminacion_exterior", name: "Techo panorámico" },
  { category: "iluminacion_exterior", name: "Cristales tintados" },
  { category: "iluminacion_exterior", name: "Llantas de aleación" },
  { category: "iluminacion_exterior", name: "Barras de techo" },
  { category: "iluminacion_exterior", name: "Enganche de remolque" },
  { category: "iluminacion_exterior", name: "Paquete exterior deportivo" },
  { category: "iluminacion_exterior", name: "Pintura metalizada o especial" },

  { category: "interior", name: "Tapicería de cuero" },
  { category: "interior", name: "Tapicería mixta" },
  { category: "interior", name: "Tapicería Alcántara" },
  { category: "interior", name: "Asientos deportivos" },
  { category: "interior", name: "Iluminación ambiental" },
  { category: "interior", name: "Reposabrazos" },
  { category: "interior", name: "Cortinillas traseras" },
  { category: "interior", name: "Asientos traseros abatibles" },
  { category: "interior", name: "Tercera fila de asientos" },
  { category: "interior", name: "Siete plazas" },
  { category: "interior", name: "Techo interior negro" },

  { category: "conduccion_prestaciones", name: "Modos de conducción" },
  { category: "conduccion_prestaciones", name: "Tracción total" },
  { category: "conduccion_prestaciones", name: "Suspensión deportiva" },
  { category: "conduccion_prestaciones", name: "Suspensión adaptativa" },
  { category: "conduccion_prestaciones", name: "Suspensión neumática" },
  {
    category: "conduccion_prestaciones",
    name: "Dirección en las cuatro ruedas",
  },
  { category: "conduccion_prestaciones", name: "Diferencial autoblocante" },
  {
    category: "conduccion_prestaciones",
    name: "Frenos deportivos o cerámicos",
  },
  { category: "conduccion_prestaciones", name: "Escape deportivo" },
  { category: "conduccion_prestaciones", name: "Paquete deportivo" },

  { category: "electricos_hibridos", name: "Bomba de calor" },
  { category: "electricos_hibridos", name: "Preacondicionamiento de batería" },
  { category: "electricos_hibridos", name: "Carga rápida" },
  { category: "electricos_hibridos", name: "Carga bidireccional o V2L" },
  { category: "electricos_hibridos", name: "Cable de carga doméstico" },
  { category: "electricos_hibridos", name: "Cable de carga Tipo 2" },
  { category: "electricos_hibridos", name: "Wallbox incluido" },
  {
    category: "electricos_hibridos",
    name: "Programación remota de carga y climatización",
  },
  {
    category: "electricos_hibridos",
    name: "Información sobre garantía de la batería",
  },
];
